-- Create the restaurant_hours table
create table if not exists public.restaurant_hours (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default timezone('utc'::text, now()),
    day_of_week smallint not null check (day_of_week >= 0 and day_of_week <= 6),
    hours tstzrange[] not null,
    timezone text not null default 'UTC',
    location_id bigint not null references public.locations(id) on delete cascade,
    last_modified timestamp with time zone not null default timezone('utc'::text, now()),
    constraint restaurant_hours_location_day_unique unique (location_id, day_of_week)
);

-- Create index for faster lookups by location
create index if not exists idx_restaurant_hours_location_id on public.restaurant_hours using btree (location_id);

-- Create index for faster lookups by day of week
create index if not exists idx_restaurant_hours_day_of_week on public.restaurant_hours using btree (day_of_week);

-- Create trigger for updating last_modified
create trigger restaurant_hours_last_modified before
update on restaurant_hours for each row
execute function update_last_modified();

-- Enable RLS
alter table public.restaurant_hours enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Users can view own restaurant hours" on public.restaurant_hours;
drop policy if exists "Users can insert own restaurant hours" on public.restaurant_hours;
drop policy if exists "Users can update own restaurant hours" on public.restaurant_hours;
drop policy if exists "Users can delete own restaurant hours" on public.restaurant_hours;

-- Create RLS policies
create policy "Users can view own restaurant hours"
    on public.restaurant_hours
    for select
    using (
        exists (
            select 1
            from public.locations l
            join public.anonymous_registrations ar on ar.id::text = l.location_registration_id::text
            where l.id = restaurant_hours.location_id
            and ar.primary_email = auth.jwt()->>'email'
        )
    );

create policy "Users can insert own restaurant hours"
    on public.restaurant_hours
    for insert
    with check (
        exists (
            select 1
            from public.locations l
            join public.anonymous_registrations ar on ar.id::text = l.location_registration_id::text
            where l.id = restaurant_hours.location_id
            and ar.primary_email = auth.jwt()->>'email'
        )
    );

create policy "Users can update own restaurant hours"
    on public.restaurant_hours
    for update
    using (
        exists (
            select 1
            from public.locations l
            join public.anonymous_registrations ar on ar.id::text = l.location_registration_id::text
            where l.id = restaurant_hours.location_id
            and ar.primary_email = auth.jwt()->>'email'
        )
    )
    with check (
        exists (
            select 1
            from public.locations l
            join public.anonymous_registrations ar on ar.id::text = l.location_registration_id::text
            where l.id = restaurant_hours.location_id
            and ar.primary_email = auth.jwt()->>'email'
        )
    );

create policy "Users can delete own restaurant hours"
    on public.restaurant_hours
    for delete
    using (
        exists (
            select 1
            from public.locations l
            join public.anonymous_registrations ar on ar.id::text = l.location_registration_id::text
            where l.id = restaurant_hours.location_id
            and ar.primary_email = auth.jwt()->>'email'
        )
    );

-- Comments
comment on table public.restaurant_hours is 'Stores restaurant operating hours for each location';
comment on column public.restaurant_hours.id is 'The primary key for the restaurant hours';
comment on column public.restaurant_hours.created_at is 'The timestamp when the hours were created';
comment on column public.restaurant_hours.day_of_week is 'The day of the week (0-6, Sunday-Saturday)';
comment on column public.restaurant_hours.hours is 'Array of time ranges for operating hours';
comment on column public.restaurant_hours.timezone is 'The timezone for the operating hours';
comment on column public.restaurant_hours.location_id is 'The foreign key to the locations table';
comment on column public.restaurant_hours.last_modified is 'The timestamp when the hours were last modified';
